from __future__ import annotations

from pathlib import Path

D1_PATH = Path(__file__).with_name("recovery_d1_runner.py")
source = D1_PATH.read_text(encoding="utf-8")

needle = '''# Post-Quick only: freeze the canonical deterministic diff review.\nrun(str(py), "-B", "skillctl.py", "repair-diff-review", "--decision", "PASS")\n'''
replacement = '''# Post-Quick only: reconcile the one known machine-local runtime byproduct\n# without making its presence a closure precondition. This is not a scope\n# exclusion. Any other path still reaches the unchanged canonical\n# repair-diff-review and remains fail-closed.\npre_diff = load(runner_temp / "recovery-h3-readonly-diff-proof.json")\nassert pre_diff["status"] == "PASS", pre_diff\nassert pre_diff["changed_paths"] == EXPECTED_CHANGED_PATHS, pre_diff\nassert pre_diff["out_of_scope_paths"] == [], pre_diff\n\nruntime_rel = "services/agent-service/runtime/vector-store/vector_store.db"\nruntime_db = ROOT / runtime_rel\nignore_file = ROOT / "services/agent-service/.gitignore"\nignore_text = ignore_file.read_text(encoding="utf-8")\nassert "# Runtime state is machine-local and never belongs to source or a release archive." in ignore_text\nassert "runtime/**" in ignore_text\n\nruntime_present = runtime_db.is_file()\ncleanup_record = {\n    "schema_version": 1,\n    "phase": "Closure-D1c-runtime-hygiene",\n    "status": "PASS",\n    "path": runtime_rel,\n    "present_after_quick": runtime_present,\n    "pre_quick_candidate_paths": pre_diff["changed_paths"],\n    "pre_quick_out_of_scope_paths": pre_diff["out_of_scope_paths"],\n    "policy": "services/agent-service/.gitignore: runtime/** is machine-local and not source/release state",\n}\n\nif runtime_present:\n    ignored = subprocess.run(["git", "check-ignore", "-q", runtime_rel], cwd=ROOT).returncode\n    tracked = subprocess.run(\n        ["git", "ls-files", "--error-unmatch", runtime_rel],\n        cwd=ROOT,\n        stdout=subprocess.DEVNULL,\n        stderr=subprocess.DEVNULL,\n    ).returncode\n    assert ignored == 0, f"runtime artifact is not covered by repository ignore policy: {runtime_rel}"\n    assert tracked != 0, f"runtime artifact unexpectedly tracked: {runtime_rel}"\n    runtime_db.unlink()\n    assert not runtime_db.exists(), f"runtime artifact cleanup failed: {runtime_rel}"\n    cleanup_record.update({\n        "action": "removed_known_machine_local_byproduct",\n        "git_ignored": True,\n        "git_tracked": False,\n    })\nelse:\n    cleanup_record.update({\n        "action": "known_machine_local_byproduct_absent",\n        "git_ignored": None,\n        "git_tracked": False,\n    })\n\n(runner_temp / "recovery-d1c-runtime-hygiene.json").write_text(\n    json.dumps(cleanup_record, ensure_ascii=False, indent=2) + "\\n",\n    encoding="utf-8",\n)\n\n# Freeze the unchanged canonical deterministic diff review after restoring (if\n# needed) the repository-defined source/release view. Exact 14-path and\n# out-of-scope assertions below remain unchanged.\nrun(str(py), "-B", "skillctl.py", "repair-diff-review", "--decision", "PASS")\n'''

if needle not in source:
    raise SystemExit("D1 post-Quick diff-review insertion point changed; fail closed")
patched = source.replace(needle, replacement, 1)
exec(compile(patched, str(D1_PATH) + "[D1c]", "exec"), {"__name__": "__main__", "__file__": str(D1_PATH)})
