"""Aggregate module-local capability definitions; no tool-name dispatcher lives here."""
from __future__ import annotations

from .list_orders import DEFINITION as LIST_ORDERS_DEFINITION
from .get_order_details import DEFINITION as GET_ORDER_DETAILS_DEFINITION
from .get_order_logistics import DEFINITION as GET_ORDER_LOGISTICS_DEFINITION
from .list_refunds import DEFINITION as LIST_REFUNDS_DEFINITION
from .list_after_sales_requests import DEFINITION as LIST_AFTER_SALES_REQUESTS_DEFINITION
from .list_invoices import DEFINITION as LIST_INVOICES_DEFINITION
from .consult_invoice_policy import DEFINITION as CONSULT_INVOICE_POLICY_DEFINITION
from .consult_refund_policy import DEFINITION as CONSULT_REFUND_POLICY_DEFINITION
from .consult_after_sales_policy import DEFINITION as CONSULT_AFTER_SALES_POLICY_DEFINITION
from .consult_warranty_policy import DEFINITION as CONSULT_WARRANTY_POLICY_DEFINITION
from .evaluate_refund_eligibility import DEFINITION as EVALUATE_REFUND_ELIGIBILITY_DEFINITION
from .prepare_cancel_order import DEFINITION as PREPARE_CANCEL_ORDER_DEFINITION
from .prepare_after_sales_request import DEFINITION as PREPARE_AFTER_SALES_REQUEST_DEFINITION
from .prepare_refund import DEFINITION as PREPARE_REFUND_DEFINITION
from .prepare_invoice import DEFINITION as PREPARE_INVOICE_DEFINITION
from .query_transaction_lifecycle import DEFINITION as QUERY_TRANSACTION_LIFECYCLE_DEFINITION
from .list_active_eligibilities import DEFINITION as LIST_ACTIVE_ELIGIBILITIES_DEFINITION
from .prepare_refund_from_eligibility import DEFINITION as PREPARE_REFUND_FROM_ELIGIBILITY_DEFINITION
from .list_active_offers import DEFINITION as LIST_ACTIVE_OFFERS_DEFINITION
from .dismiss_offer import DEFINITION as DISMISS_OFFER_DEFINITION
from .dismiss_eligibility import DEFINITION as DISMISS_ELIGIBILITY_DEFINITION
from .ask_context_clarification import DEFINITION as ASK_CONTEXT_CLARIFICATION_DEFINITION
from .report_unsupported_request import DEFINITION as REPORT_UNSUPPORTED_REQUEST_DEFINITION

CAPABILITIES = (
    LIST_ORDERS_DEFINITION,
    GET_ORDER_DETAILS_DEFINITION,
    GET_ORDER_LOGISTICS_DEFINITION,
    LIST_REFUNDS_DEFINITION,
    LIST_AFTER_SALES_REQUESTS_DEFINITION,
    LIST_INVOICES_DEFINITION,
    CONSULT_INVOICE_POLICY_DEFINITION,
    CONSULT_REFUND_POLICY_DEFINITION,
    CONSULT_AFTER_SALES_POLICY_DEFINITION,
    CONSULT_WARRANTY_POLICY_DEFINITION,
    EVALUATE_REFUND_ELIGIBILITY_DEFINITION,
    PREPARE_CANCEL_ORDER_DEFINITION,
    PREPARE_AFTER_SALES_REQUEST_DEFINITION,
    PREPARE_REFUND_DEFINITION,
    PREPARE_INVOICE_DEFINITION,
    QUERY_TRANSACTION_LIFECYCLE_DEFINITION,
    LIST_ACTIVE_ELIGIBILITIES_DEFINITION,
    PREPARE_REFUND_FROM_ELIGIBILITY_DEFINITION,
    LIST_ACTIVE_OFFERS_DEFINITION,
    DISMISS_OFFER_DEFINITION,
    DISMISS_ELIGIBILITY_DEFINITION,
    ASK_CONTEXT_CLARIFICATION_DEFINITION,
    REPORT_UNSUPPORTED_REQUEST_DEFINITION,
)

BY_TOOL_NAME = {row.tool_name: row for row in CAPABILITIES}
BY_KEY = {row.key: row for row in CAPABILITIES}

def definition_for_tool(tool_name: str):
    return BY_TOOL_NAME.get(str(tool_name or ""))
