from __future__ import annotations

from typing import Protocol, Any, runtime_checkable
from dataclasses import dataclass
from enum import StrEnum


@dataclass(frozen=True)
class TransactionScope:
    """Customer-visible transaction scope.

    Tenant and user are mandatory boundaries. Thread is an optional filter only
    so transaction history remains available across chats/devices.
    """

    tenant_id: str
    user_id: str
    thread_id: str | None = None


class ActiveDraftValidationCode(StrEnum):
    OK = "ok"
    NOT_FOUND = "not_found"
    SCOPE_MISMATCH = "scope_mismatch"
    REVISION_MISMATCH = "revision_mismatch"
    STATE_NOT_ALLOWED = "state_not_allowed"
    EXPIRED = "expired"
    REVOKED = "revoked"


@dataclass(frozen=True)
class ActiveDraftValidationResult:
    code: ActiveDraftValidationCode
    draft: dict[str, Any] | None = None




@runtime_checkable
class ThreadRepository(Protocol):
    def claim_or_validate_thread(self, thread_id: str, user_id: str, tenant_id: str | None = None) -> dict: ...
    def upsert_thread(self, thread_id: str, user_id: str | None = None, summary: str | None = None, tenant_id: str | None = None) -> None: ...
    def get_thread(self, thread_id: str) -> dict | None: ...
    def assert_thread_owner(self, thread_id: str, user_id: str, tenant_id: str | None = None) -> dict: ...
    def list_threads(self, user_id: str | None = None, limit: int = 100, tenant_id: str | None = None) -> list[dict]: ...


@runtime_checkable
class MessageRepository(Protocol):
    def add_message(self, thread_id: str, role: str, content: str, *, message_type: str | None = None, presentation: list[dict[str, Any]] | None = None, interaction: dict[str, Any] | None = None) -> None: ...
    def list_messages(self, thread_id: str, limit: int = 50) -> list[dict]: ...


@runtime_checkable
class TraceRepository(Protocol):
    def log_event(self, thread_id: str, user_id: str | None, event_type: str, node: str | None = None, input_data: Any | None = None, output_data: Any | None = None, latency_ms: int | None = None, trace_id: str | None = None, correlation_id: str | None = None) -> str: ...
    def list_recent(self, limit: int = 100) -> list[dict]: ...
    def list_recent_by_event_type(self, event_type: str, limit: int = 100) -> list[dict]: ...
    def list_by_thread(self, thread_id: str, limit: int = 200) -> list[dict]: ...
    def get_trace(self, trace_log_id: int) -> dict | None: ...
    def prune_older_than(self, cutoff_iso: str) -> int: ...


@runtime_checkable
class ActionAuditRepository(Protocol):
    def log_action(self, *, thread_id: str | None, user_id: str | None, role: str | None, action_name: str, idempotency_key: str | None, status: str, input_data: Any, output_data: Any) -> None: ...
    def list_recent(self, limit: int = 100) -> list[dict]: ...
    def prune_older_than(self, cutoff_iso: str) -> int: ...


@runtime_checkable
class IdempotencyRepository(Protocol):
    def get(self, key: str | None) -> dict[str, Any] | None: ...
    def start(self, *, key: str, action_name: str, request_hash: str) -> dict[str, Any]: ...
    def finish(self, *, key: str, status: str, result: Any, error: str | None = None) -> None: ...


@runtime_checkable
class ActionLockRepository(Protocol):
    def acquire(self, lock_key: str, *, owner: str | None = None, ttl_seconds: int = 120) -> dict[str, Any]: ...
    def renew(self, lock_key: str, *, owner: str, fencing_token: int, ttl_seconds: int = 120) -> dict[str, Any]: ...
    def validate(self, lock_key: str, *, owner: str, fencing_token: int) -> bool: ...
    def release(self, lock_key: str, owner: str | None = None, fencing_token: int | None = None) -> None: ...


class OutboxRepository(Protocol):
    def enqueue(self, *, event_type: str, aggregate_key: str | None, payload: Any) -> int: ...
    def list_pending(self, limit: int = 100) -> list[dict[str, Any]]: ...
    def list_recent(self, limit: int = 100) -> list[dict[str, Any]]: ...


@runtime_checkable
class ActionRunRepository(Protocol):
    def start(self, *, idempotency_key: str | None, action_name: str) -> str: ...
    def transition(self, run_id: str, status: str, *, detail: Any = None) -> None: ...
    def get(self, run_id: str) -> dict[str, Any] | None: ...
    def find_by_idempotency_key(self, idempotency_key: str | None) -> dict[str, Any] | None: ...
    def list_recent(self, limit: int = 100) -> list[dict[str, Any]]: ...


class TransactionLifecycleRepository(Protocol):
    """Single, scope-first Agent transaction contract.

    Concrete SQLite/SQLAlchemy providers may retain internal convenience
    methods, but Customer APIs, ContextBundle and use cases must use the methods
    below so they cannot bypass tenant/user boundaries.
    """

    def create_draft(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_draft(self, draft_id: str | None) -> dict[str, Any] | None: ...
    def get_draft_for_scope(self, *, scope: TransactionScope, draft_id: str) -> dict[str, Any] | None: ...
    def list_drafts_for_scope(self, *, scope: TransactionScope, states: set[str] | None = None, limit: int = 50, cursor: str | None = None) -> list[dict[str, Any]]: ...
    def validate_active_draft(self, *, scope: TransactionScope, draft_id: str, expected_revision: int | None = None, allowed_states: set[str] | None = None) -> ActiveDraftValidationResult: ...
    def advance_draft(self, draft_id: str, *, draft_state: str, **kwargs: Any) -> None: ...

    def issue_grant(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_grant(self, grant_id: str | None) -> dict[str, Any] | None: ...
    def list_grants_by_thread(self, *, tenant_id: str, user_id: str, thread_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    def reserve_grant(self, grant_id: str, *, attempt_id: str | None = None) -> dict[str, Any]: ...
    def reserve_grant_and_start_attempt(self, **kwargs: Any) -> dict[str, Any]: ...
    def consume_grant(self, grant_id: str, *, attempt_id: str | None = None, receipt_handle: str | None = None) -> None: ...
    def revoke_grant(self, grant_id: str, *, reason: str) -> None: ...

    def start_attempt(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_attempt(self, attempt_id: str | None) -> dict[str, Any] | None: ...
    def get_attempt_for_scope(self, *, scope: TransactionScope, attempt_id: str) -> dict[str, Any] | None: ...
    def get_attempt_by_idempotency_key(self, idempotency_key: str | None) -> dict[str, Any] | None: ...
    def list_attempts_for_draft(self, *, scope: TransactionScope, draft_id: str) -> list[dict[str, Any]]: ...
    def transition_attempt(self, attempt_id: str, *, state: str, **kwargs: Any) -> None: ...
    def list_reconcilable_attempts(self, *, scope: TransactionScope | None = None, tenant_id: str | None = None, user_id: str | None = None, thread_id: str | None = None, limit: int = 20) -> list[dict[str, Any]]: ...
    def list_by_thread(self, *, tenant_id: str, user_id: str, thread_id: str, limit: int = 100) -> list[dict[str, Any]]: ...

    def record_receipt(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_receipt_for_attempt(self, *, scope: TransactionScope, attempt_id: str) -> dict[str, Any] | None: ...
    def get_latest_receipt_for_draft(self, *, scope: TransactionScope, draft_id: str) -> dict[str, Any] | None: ...


class StoreProvider(Protocol):
    threads: ThreadRepository
    messages: MessageRepository
    traces: TraceRepository
    action_audits: ActionAuditRepository
    idempotency: IdempotencyRepository
    locks: ActionLockRepository
    outbox: OutboxRepository
    action_runs: ActionRunRepository
    transactions: TransactionLifecycleRepository

    def close(self) -> None: ...
